# Generated by Django 4.2.5 on 2023-10-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_enquiry_courses_enquiry_date_alter_enquiry_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C')], default='python', max_length=20)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
